on: [push]

jobs:
  sigma_analysis:
    runs-on: ubuntu-latest
    name: Analyze repository using the SIGMA Analysis Engine
    steps:
    - name: SIGMA Analysis step
      id: sigma
      uses: jfitzpatrick99/sigma-action@v2
    # Use the output from the SIGMA step
    - name: Get the results file
      run: echo "Results written to ${{ steps.sigma.outputs.results }}"
